.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH rwpspread 1  "rwpspread 0.2.1-1" 
.SH NAME
rwpspread \- Multi\-Monitor Wallpaper Utility
.SH SYNOPSIS
\fBrwpspread\fR <\fB\-i\fR|\fB\-\-image\fR> [\fB\-a\fR|\fB\-\-align\fR] [\fB\-b\fR|\fB\-\-backend\fR] [\fB\-d\fR|\fB\-\-daemon\fR] [\fB\-p\fR|\fB\-\-palette\fR] [\fB\-s\fR|\fB\-\-swaylock\fR] [\fB\-f\fR|\fB\-\-force\-resplit\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Multi\-Monitor Wallpaper Utility
.SH OPTIONS
.TP
\fB\-i\fR, \fB\-\-image\fR=\fIIMAGE\fR
Image file path
.TP
\fB\-a\fR, \fB\-\-align\fR=\fIALIGN\fR
Do not downscale the base image, align the layout instead
.br

.br
[\fIpossible values: \fRtl, tr, tc, bl, br, bc, rc, lc, c]
.TP
\fB\-b\fR, \fB\-\-backend\fR=\fIBACKEND\fR
Wallpaper setter backend
.br

.br
[\fIpossible values: \fRwpaperd, swaybg]
.TP
\fB\-d\fR, \fB\-\-daemon\fR
Enable daemon mode, will watch and resplit on output changes
.TP
\fB\-p\fR, \fB\-\-palette\fR
Generate a color palette from input image
.TP
\fB\-s\fR, \fB\-\-swaylock\fR
Use swaylock integration
.TP
\fB\-f\fR, \fB\-\-force\-resplit\fR
Force resplit, skips all image cache checks
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.2.1\-1
