name: Build and Upload

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build dynamic linked
        run: cargo build --release --verbose
      - name: Build static linked
        run: RUSTFLAGS='-C target-feature=-crt-static' cargo build --target=x86_64-unknown-linux-gnu --release --verbose
      - name: Build musl static linked
        run: |
          rustup target add x86_64-unknown-linux-musl
          cargo build --target=x86_64-unknown-linux-musl --release --verbose
      - name: Rename binaries
        run: |
          mv target/x86_64-unknown-linux-gnu/release/rwpspread target/release/rwpspread_gnu
          mv target/x86_64-unknown-linux-musl/release/rwpspread target/release/rwpspread_musl
      - name: Upload gnu binary
        uses: actions/upload-artifact@v3
        with:
          path: target/x86_64-unknown-linux-gnu/release/rwpspread_gnu
      - name: Upload musl binary
        uses: actions/upload-artifact@v3
        with:
          path: target/x86_64-unknown-linux-musl/release/rwpspread_musl
