name: Build for x86 and aarch64

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'build.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'build.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-x86:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build GNU static linked
        env:
          RUSTFLAGS: -C target-feature=+crt-static
        run: cargo build --target=x86_64-unknown-linux-gnu --release --verbose
      - name: Build musl static linked
        run: |
          rustup target add x86_64-unknown-linux-musl
          cargo build --target=x86_64-unknown-linux-musl --release --verbose
      - name: Move and generate checksums
        run: |
          mv target/x86_64-unknown-linux-gnu/release/rwpspread ./rwpspread-x86_64-unknown-linux-gnu
          mv target/x86_64-unknown-linux-musl/release/rwpspread ./rwpspread-x86_64-unknown-linux-musl
          sha512sum ./rwpspread-x86_64-unknown-linux-gnu > ./rwpspread-x86_64-unknown-linux-gnu.sha512sum
          sha512sum ./rwpspread-x86_64-unknown-linux-musl > ./rwpspread-x86_64-unknown-linux-musl.sha512sum
      - name: Upload release files
        uses: actions/upload-artifact@v4
        with:
          name: rwpspread-x86_64
          path: |
            rwpspread-x86_64-unknown-linux-gnu
            rwpspread-x86_64-unknown-linux-gnu.sha512sum
            rwpspread-x86_64-unknown-linux-musl
            rwpspread-x86_64-unknown-linux-musl.sha512sum
  build-aarch64:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build GNU static linked
        env:
          RUSTFLAGS: -C target-feature=+crt-static -C linker=aarch64-linux-gnu-gcc
        run: |
          sudo apt update && sudo apt install -y gcc-aarch64-linux-gnu
          rustup target add aarch64-unknown-linux-gnu
          cargo build --target=aarch64-unknown-linux-gnu --release --verbose
      - name: Build musl static linked
        run: |
          sudo apt update && sudo apt install -y musl-tools build-essential
          rustup target add aarch64-unknown-linux-musl
          cargo build --target=aarch64-unknown-linux-musl --release --verbose
      - name: Move and generate checksums
        run: |
          mv target/aarch64-unknown-linux-gnu/release/rwpspread ./rwpspread-aarch64-unknown-linux-gnu
          mv target/aarch64-unknown-linux-musl/release/rwpspread ./rwpspread-aarch64-unknown-linux-musl
          sha512sum ./rwpspread-aarch64-unknown-linux-gnu > ./rwpspread-aarch64-unknown-linux-gnu.sha512sum
          sha512sum ./rwpspread-aarch64-unknown-linux-musl > ./rwpspread-aarch64-unknown-linux-musl.sha512sum
      - name: Upload release files
        uses: actions/upload-artifact@v4
        with:
          name: rwpspread-aarch64
          path: |
            rwpspread-aarch64-unknown-linux-gnu
            rwpspread-aarch64-unknown-linux-gnu.sha512sum
            rwpspread-aarch64-unknown-linux-musl
            rwpspread-aarch64-unknown-linux-musl.sha512sum
