name: Build and Upload

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build GNU static linked
        run: RUSTFLAGS='-C target-feature=-crt-static' cargo build --target=x86_64-unknown-linux-gnu --release --verbose
      - name: Build musl static linked
        run: |
          rustup target add x86_64-unknown-linux-musl
          cargo build --target=x86_64-unknown-linux-musl --release --verbose
      - name: Rename binaries
        run: |
          mv target/x86_64-unknown-linux-musl/release/rwpspread target/x86_64-unknown-linux-musl/release/rwpspread_musl
      - name: Generate Checksums
        run: |
          sha512sum target/x86_64-unknown-linux-gnu/release/rwpspread > target/x86_64-unknown-linux-gnu/release/rwpspread.sha512sum
          sha512sum target/x86_64-unknown-linux-musl/release/rwpspread_musl > target/x86_64-unknown-linux-musl/release/rwpspread_musl.sha512sum
      - name: Upload GNU release files
        uses: actions/upload-artifact@v4
        with:
          path: target/x86_64-unknown-linux-gnu/release/rwpspread*
      - name: Upload musl release files
        uses: actions/upload-artifact@v4
        with:
          path: target/x86_64-unknown-linux-musl/release/rwpspread_musl*
