name: Build for aarch64

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src/**'
      - '.github/workflows/build_aarch64.yaml'
      - 'build.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/**'
      - '.github/workflows/build_aarch64.yaml'
      - 'build.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build GNU static linked
        run: |
          sudo apt update && sudo apt install -y gcc-aarch64-linux-gnu
          rustup target add aarch64-unknown-linux-gnu
          RUSTFLAGS="-C target-feature=+crt-static -C linker=aarch64-linux-gnu-gcc" cargo build --target=aarch64-unknown-linux-gnu --release --verbose
      - name: Generate Checksums
        run: |
          sha512sum target/aarch64-unknown-linux-gnu/release/rwpspread > target/aarch64-unknown-linux-gnu/release/rwpspread.sha512sum
      - name: Upload release files
        uses: actions/upload-artifact@v4
        with:
          name: rwpspread-aarch64
          path: |
            target/aarch64-unknown-linux-gnu/release/rwpspread
            target/aarch64-unknown-linux-gnu/release/rwpspread.sha512sum
