name: "Publish"

on:
  workflow_dispatch:
  release:
    types: [ "published" ]

jobs:
  publish-cratesio:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Publish crates.io Package
        run: cargo publish --token ${CRATES_AUTH_TOKEN} 
        env:
          CRATES_AUTH_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
  build-all-for-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Prepare environment
        run: |
          sudo apt update && sudo apt install -y build-essential gcc-aarch64-linux-gnu
          rustup target add aarch64-unknown-linux-gnu aarch64-unknown-linux-musl x86_64-unknown-linux-gnu x86_64-unknown-linux-musl
      - name: Build x86 GNU static linked
        env:
          RUSTFLAGS: -C target-feature=+crt-static
        run: cargo build --target=x86_64-unknown-linux-gnu --release --verbose
      - name: Build x86 musl static linked
        env:
          RUSTFLAGS: -C target-feature=+crt-static
        run: |
          cargo build --target=x86_64-unknown-linux-musl --release --verbose
      - name: Build arm64 GNU static linked
        env:
          RUSTFLAGS: -C target-feature=+crt-static -C linker=aarch64-linux-gnu-gcc
        run: |
          cargo build --target=aarch64-unknown-linux-gnu --release --verbose
      - name: Build arm64 musl static linked
        env:
          RUSTFLAGS: -C target-feature=+crt-static
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER: aarch64-linux-gnu-gcc
          CC: aarch64-linux-gnu-gcc
        run: |
          cargo build --target=aarch64-unknown-linux-musl --release --verbose
      - name: Move and generate checksums
        run: |
          mkdir ./release_output/
          mv target/x86_64-unknown-linux-gnu/release/rwpspread ./release_output/rwpspread-x86_64-unknown-linux-gnu
          mv target/x86_64-unknown-linux-musl/release/rwpspread ./release_output/rwpspread-x86_64-unknown-linux-musl
          mv target/aarch64-unknown-linux-gnu/release/rwpspread ./release_output/rwpspread-aarch64-unknown-linux-gnu
          mv target/aarch64-unknown-linux-musl/release/rwpspread ./release_output/rwpspread-aarch64-unknown-linux-musl
          sha512sum ./release_output/rwpspread-x86_64-unknown-linux-gnu > ./release_output/rwpspread-x86_64-unknown-linux-gnu.sha512sum
          sha512sum ./release_output/rwpspread-x86_64-unknown-linux-musl > ./release_output/rwpspread-x86_64-unknown-linux-musl.sha512sum
          sha512sum ./release_output/rwpspread-aarch64-unknown-linux-gnu > ./release_output/rwpspread-aarch64-unknown-linux-gnu.sha512sum
          sha512sum ./release_output/rwpspread-aarch64-unknown-linux-musl > ./release_output/rwpspread-aarch64-unknown-linux-musl.sha512sum
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./release_output/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
